language: ruby

before_install:
  - gem update bundler

before_script:
  - wget -O db/schema.rb 'https://raw.githubusercontent.com/openfoodfoundation/openfoodnetwork/master/db/schema.rb'
  - bundle exec rake db:create db:test:prepare
