development:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_dev
  pool: 5
  host: localhost
  username: ofn
  password: f00d

test:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_test
  username: ofn
  password: f00d

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: localhost

staging:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: localhost
